"""
Fine-tune DistilBERT for Lithium 7-class notification classification and export to ONNX.

This script:
1. Loads training data from CSV (generated by generate_data.py)
2. Fine-tunes distilbert-base-uncased for 7-class sequence classification
3. Evaluates on the validation set
4. Exports the model to ONNX format (optimized for mobile)
5. Copies vocab.txt alongside the ONNX model

The exported model expects two inputs:
    - input_ids: int64[1, 128]
    - attention_mask: int64[1, 128]
And produces:
    - logits: float32[1, 7]

Usage:
    # Step 1: Generate data
    python generate_data.py

    # Step 2: Train and export
    python train_classifier.py

    # Step 3: Sideload to device
    adb push output/classification_v1.onnx /data/local/tmp/
    adb push output/vocab.txt /data/local/tmp/
    adb shell run-as ai.talkingrock.lithium.debug cp /data/local/tmp/classification_v1.onnx files/models/
    adb shell run-as ai.talkingrock.lithium.debug cp /data/local/tmp/vocab.txt files/models/

Options:
    --model         Base model (default: distilbert-base-uncased)
    --epochs        Training epochs (default: 5)
    --batch-size    Batch size (default: 32)
    --lr            Learning rate (default: 2e-5)
    --max-length    Max sequence length (default: 128, must match WordPieceTokenizer.MAX_SEQ_LEN)
    --output-dir    Output directory for ONNX model (default: output/)
    --data-dir      Directory containing train.csv and val.csv (default: data/)
"""

import argparse
import os
import shutil
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from datasets import Dataset
from sklearn.metrics import classification_report, confusion_matrix
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    Trainer,
    TrainingArguments,
)


LABEL_NAMES = [
    "personal",         # 0
    "engagement_bait",  # 1
    "promotional",      # 2
    "transactional",    # 3
    "system",           # 4
    "social_signal",    # 5
    "unknown",          # 6
]

NUM_LABELS = len(LABEL_NAMES)


def load_data(data_dir: str):
    """Load train and val CSVs into HuggingFace Datasets."""
    train_df = pd.read_csv(os.path.join(data_dir, "train.csv"))
    val_df = pd.read_csv(os.path.join(data_dir, "val.csv"))

    # Verify labels are integers 0-6
    assert train_df["label"].min() >= 0 and train_df["label"].max() < NUM_LABELS
    assert val_df["label"].min() >= 0 and val_df["label"].max() < NUM_LABELS

    train_ds = Dataset.from_pandas(train_df[["text", "label"]])
    val_ds = Dataset.from_pandas(val_df[["text", "label"]])

    print(f"Loaded {len(train_ds)} training and {len(val_ds)} validation examples")
    return train_ds, val_ds


def tokenize_dataset(dataset, tokenizer, max_length):
    """Tokenize a dataset using the model's tokenizer."""
    def tokenize_fn(examples):
        return tokenizer(
            examples["text"],
            padding="max_length",
            truncation=True,
            max_length=max_length,
        )
    return dataset.map(tokenize_fn, batched=True, remove_columns=["text"])


def compute_metrics(eval_pred):
    """Compute accuracy for the Trainer."""
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    accuracy = (predictions == labels).mean()
    return {"accuracy": accuracy}


def train(args):
    """Fine-tune the model and export to ONNX."""
    print(f"\n{'='*60}")
    print(f"Lithium Notification Classifier Training")
    print(f"{'='*60}")
    print(f"Model:      {args.model}")
    print(f"Epochs:     {args.epochs}")
    print(f"Batch size: {args.batch_size}")
    print(f"LR:         {args.lr}")
    print(f"Max length: {args.max_length}")
    print(f"{'='*60}\n")

    # Load data
    train_ds, val_ds = load_data(args.data_dir)

    # Load tokenizer and model
    print(f"Loading tokenizer and model: {args.model}")
    tokenizer = AutoTokenizer.from_pretrained(args.model)
    model = AutoModelForSequenceClassification.from_pretrained(
        args.model,
        num_labels=NUM_LABELS,
        id2label={i: name for i, name in enumerate(LABEL_NAMES)},
        label2id={name: i for i, name in enumerate(LABEL_NAMES)},
    )

    # Tokenize datasets
    print("Tokenizing datasets...")
    train_ds = tokenize_dataset(train_ds, tokenizer, args.max_length)
    val_ds = tokenize_dataset(val_ds, tokenizer, args.max_length)

    # Set format for PyTorch
    train_ds.set_format("torch")
    val_ds.set_format("torch")

    # Training arguments
    checkpoint_dir = os.path.join(args.output_dir, "checkpoints")
    training_args = TrainingArguments(
        output_dir=checkpoint_dir,
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.batch_size * 2,
        learning_rate=args.lr,
        weight_decay=0.01,
        warmup_ratio=0.1,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="accuracy",
        greater_is_better=True,
        logging_steps=50,
        report_to="none",  # no wandb/tensorboard
        fp16=torch.cuda.is_available(),
        dataloader_num_workers=0,  # avoid multiprocessing issues
    )

    # Trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        compute_metrics=compute_metrics,
    )

    # Train
    print("\nStarting training...")
    trainer.train()

    # Evaluate
    print("\nEvaluating on validation set...")
    eval_result = trainer.evaluate()
    print(f"Validation accuracy: {eval_result['eval_accuracy']:.4f}")

    # Detailed classification report
    predictions = trainer.predict(val_ds)
    pred_labels = np.argmax(predictions.predictions, axis=-1)
    true_labels = predictions.label_ids

    print("\nClassification Report:")
    print(classification_report(
        true_labels, pred_labels,
        target_names=LABEL_NAMES,
        digits=3,
    ))

    print("Confusion Matrix:")
    cm = confusion_matrix(true_labels, pred_labels)
    # Print with labels
    header = "          " + " ".join(f"{n[:5]:>6}" for n in LABEL_NAMES)
    print(header)
    for i, row in enumerate(cm):
        label = f"{LABEL_NAMES[i][:10]:<10}"
        print(label + " ".join(f"{v:>6}" for v in row))

    # Save the fine-tuned model (PyTorch format)
    model_save_dir = os.path.join(args.output_dir, "pytorch_model")
    print(f"\nSaving fine-tuned model to {model_save_dir}")
    trainer.save_model(model_save_dir)
    tokenizer.save_pretrained(model_save_dir)

    # Export to ONNX
    export_onnx(model_save_dir, args.output_dir, args.max_length, args.model)

    # Quantize the ONNX model (INT8 dynamic quantization — ~4x smaller)
    quantize_onnx(args.output_dir)

    # Copy vocab.txt
    copy_vocab(model_save_dir, args.output_dir)

    print(f"\n{'='*60}")
    print(f"Done! Model exported to {args.output_dir}/")
    print(f"Files to sideload (use quantized for mobile):")
    print(f"  {args.output_dir}/classification_v1.onnx          (full precision)")
    print(f"  {args.output_dir}/classification_v1_quantized.onnx (INT8, ~4x smaller)")
    print(f"  {args.output_dir}/vocab.txt")
    print(f"{'='*60}")


def export_onnx(model_dir: str, output_dir: str, max_length: int, base_model: str):
    """Export the fine-tuned model to ONNX format using optimum."""
    print(f"\nExporting to ONNX...")

    onnx_path = os.path.join(output_dir, "onnx_export")
    os.makedirs(onnx_path, exist_ok=True)

    try:
        from optimum.onnxruntime import ORTModelForSequenceClassification

        # Load the fine-tuned model and export to ONNX
        ort_model = ORTModelForSequenceClassification.from_pretrained(
            model_dir,
            export=True,
        )
        ort_model.save_pretrained(onnx_path)

        # Find the exported .onnx file and rename to classification_v1.onnx
        onnx_files = list(Path(onnx_path).glob("*.onnx"))
        if onnx_files:
            src = onnx_files[0]
            dst = Path(output_dir) / "classification_v1.onnx"
            shutil.copy2(src, dst)
            size_mb = dst.stat().st_size / (1024 * 1024)
            print(f"  ONNX model: {dst} ({size_mb:.1f} MB)")
        else:
            print("  WARNING: No .onnx file found in export — falling back to manual export")
            _export_onnx_manual(model_dir, output_dir, max_length)

    except ImportError:
        print("  optimum not available — falling back to manual ONNX export")
        _export_onnx_manual(model_dir, output_dir, max_length)


def quantize_onnx(output_dir: str):
    """Apply INT8 dynamic quantization to reduce model size ~4x."""
    from onnxruntime.quantization import quantize_dynamic, QuantType

    src = os.path.join(output_dir, "classification_v1.onnx")
    dst = os.path.join(output_dir, "classification_v1_quantized.onnx")

    if not os.path.exists(src):
        print("  WARNING: cannot quantize — source ONNX model not found")
        return

    print("  Quantizing to INT8 (dynamic)...")
    quantize_dynamic(
        model_input=src,
        model_output=dst,
        weight_type=QuantType.QUInt8,
    )

    src_mb = os.path.getsize(src) / (1024 * 1024)
    dst_mb = os.path.getsize(dst) / (1024 * 1024)
    ratio = src_mb / dst_mb if dst_mb > 0 else 0
    print(f"  Full:      {src} ({src_mb:.1f} MB)")
    print(f"  Quantized: {dst} ({dst_mb:.1f} MB, {ratio:.1f}x smaller)")


def _export_onnx_manual(model_dir: str, output_dir: str, max_length: int):
    """Manual ONNX export using torch.onnx.export (fallback)."""
    model = AutoModelForSequenceClassification.from_pretrained(model_dir)
    model.eval()

    # Create dummy inputs
    dummy_input_ids = torch.ones(1, max_length, dtype=torch.long)
    dummy_attention_mask = torch.ones(1, max_length, dtype=torch.long)

    onnx_path = os.path.join(output_dir, "classification_v1.onnx")

    torch.onnx.export(
        model,
        (dummy_input_ids, dummy_attention_mask),
        onnx_path,
        input_names=["input_ids", "attention_mask"],
        output_names=["logits"],
        dynamic_axes={
            "input_ids": {0: "batch_size"},
            "attention_mask": {0: "batch_size"},
            "logits": {0: "batch_size"},
        },
        opset_version=14,
        do_constant_folding=True,
    )

    size_mb = os.path.getsize(onnx_path) / (1024 * 1024)
    print(f"  ONNX model: {onnx_path} ({size_mb:.1f} MB)")


def copy_vocab(model_dir: str, output_dir: str):
    """Copy the tokenizer's vocab.txt to the output directory."""
    vocab_src = os.path.join(model_dir, "vocab.txt")
    vocab_dst = os.path.join(output_dir, "vocab.txt")

    if os.path.exists(vocab_src):
        shutil.copy2(vocab_src, vocab_dst)
        line_count = sum(1 for _ in open(vocab_dst))
        print(f"  Vocab: {vocab_dst} ({line_count} tokens)")
    else:
        # For models that don't have vocab.txt (e.g., sentencepiece), create from tokenizer
        print(f"  WARNING: vocab.txt not found at {vocab_src}")
        print(f"  Generating from tokenizer vocabulary...")
        tokenizer = AutoTokenizer.from_pretrained(model_dir)
        vocab = tokenizer.get_vocab()
        # Sort by ID (value) to get ordered vocab
        sorted_vocab = sorted(vocab.items(), key=lambda x: x[1])
        with open(vocab_dst, "w", encoding="utf-8") as f:
            for token, _ in sorted_vocab:
                f.write(f"{token}\n")
        print(f"  Vocab: {vocab_dst} ({len(sorted_vocab)} tokens)")


def main():
    parser = argparse.ArgumentParser(
        description="Train Lithium notification classifier and export to ONNX"
    )
    parser.add_argument("--model", type=str, default="distilbert-base-uncased",
                        help="Base model (default: distilbert-base-uncased)")
    parser.add_argument("--epochs", type=int, default=5,
                        help="Training epochs (default: 5)")
    parser.add_argument("--batch-size", type=int, default=32,
                        help="Batch size (default: 32)")
    parser.add_argument("--lr", type=float, default=2e-5,
                        help="Learning rate (default: 2e-5)")
    parser.add_argument("--max-length", type=int, default=128,
                        help="Max sequence length (default: 128)")
    parser.add_argument("--output-dir", type=str, default="output",
                        help="Output directory (default: output/)")
    parser.add_argument("--data-dir", type=str, default="data",
                        help="Data directory with train.csv/val.csv (default: data/)")
    args = parser.parse_args()

    train(args)


if __name__ == "__main__":
    main()
